-- AlterTable
ALTER TABLE "Admin" ALTER COLUMN "name" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "name" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "name" DROP NOT NULL;
